import type { ProjectInput } from "./schema";

export const projectsRaw = [
  {
    slug: "podorozhnyky",
    order: 10,
    year: 2025,
    category: "web",
    href: "https://project-group-6-podorozhnyky-front.vercel.app/",
    kind: { uk: "Blog", en: "Blog" },
    title: { uk: "Подорожники", en: "Podorozhnyky" },
    summary: {
      uk: "Цей проєкт розроблений для мандрівників та всіх, хто хоче поділитися своїми пригодами. Платформа дозволяє користувачам: Публікувати власні історії подорожей Переглядати історії інших користувачів Зберігати улюблені історії Вести профіль мандрівника Зв'язуватися з новими людьми та відкривати для себе нові напрямки.",
      en: "This project is designed for travelers and anyone who wants to share their adventures. The platform allows users to: Publish their own travel stories Browse stories from other users Save favorite stories Maintain a traveler profile Connect with new people and discover new destinations.",
    },
    cover: {
      src: "/projects/podorozhnyky.webp",
      width: 1200,
      height: 800,
      alt: {
        uk: "Подорожники",
        en: "Screenshot of the Podorozhnyky blog",
      },
    },
    stack: [
      "React",
      "Node.js",
      "Express MongoDB",
      "TypeScript",
      "React Hot Toast",
      "Formik",
      "React Select",
      "Tailwind CSS",
      "React Icons",
      "React Query",
      "Mongoose JWT",
      "Yup Axios",
      "Next.js",
      "GitHub",
      "Git",
    ],
  },
  {
    slug: "booksy",
    order: 20,
    year: 2025,
    category: "web",
    href: "https://nikolka44.github.io/project-BooksyTeam4/",
    kind: { uk: "e-commerce", en: "e-commerce" },
    title: "Booksy",
    summary: {
      uk: "Booksy — це односторінковий веб-сайт (SPA), розроблений для демонстрації каталогу книг з можливістю перегляду детальної інформації про книгу, фільтрації за категоріями та взаємодії з модальними вікнами (покупка, реєстрація, контакт).",
      en: "Booksy is a single-page website (SPA) designed to showcase a catalog of books with the ability to view book details, filter by category, and interact with modal windows (purchase, registration, contact).",
    },
    cover: {
      src: "/projects/booksy.webp",
      width: 1200,
      height: 800,
      alt: {
        uk: "Скріншот застосунку Booksy",
        en: "Screenshot of the Booksy app",
      },
    },
    stack: ["HTML5", "JavaScript", "CSS", "GitHub", "Git"],
  },
  {
    slug: "notehub",
    order: 30,
    year: 2025,
    category: "web",
    href: "https://note-hub-green.vercel.app/",
    kind: { uk: "To-do ліст", en: "To-do list" },
    title: "NoteHub",
    summary: {
      uk: "Легкий та ефективний додаток для створення нотаток, призначений для організації особистих думок та інформації. Додаток дозволяє користувачам: Створювати нові нотатки (назва, вміст та категорія), шукати нотатки в режимі реального часу, навігацію нотатками за допомогою пагінації, керувати та структурувати інформацію в простому та інтуїтивно зрозумілому інтерфейсі. Проект зосереджений на чистій архітектурі, ефективному управлінні станом та адаптивному користувацькому досвіді.",
      en: "A lightweight and efficient note-taking application designed for organizing personal thoughts and information.The application allows users to:- Create new notes (title, content, and category) - Search notes in real time - Navigate through notes using pagination - Manage and structure information in a simple and intuitive interface. The project focuses on clean architecture, efficient state management, and responsive user experience.",
    },
    cover: {
      src: "/projects/notehub.webp",
      width: 1200,
      height: 800,
      alt: {
        uk: "NoteHub",
        en: "NoteHub",
      },
    },
    stack: [
      "React",
      "Vite",
      "Axios",
      "TanStack React Query (useQuery, keepPreviousData)",
      "Formik + Yup (form handling and validation)",
      "React Paginate",
      "use-debounce",
      "REST API",
    ],
  },
  {
    slug: "ai-powered-automation-for-client-request-filtering",
    order: 50,
    year: 2026,
    category: "automation",
    href: "https://quill-haze-d51.notion.site/AI-Powered-automation-for-client-request-filtering-38ac423a711e801d9923f3a3dc241213",
    kind: {
      uk: "Автоматизація на базі штучного інтелекту",
      en: "Artificial intelligence-based automation",
    },
    title: {
      uk: "Автоматизація на базі ШІ для фільтрації клієнтських запитів",
      en: "AI-based automation for filtering customer requests",
    },
    summary: {
      uk: "Автоматизація якості дзвінків на базі штучного інтелекту для електронної комерції",
      en: "AI-Powered Call-Quality Automation for E-Commerce",
    },
    cover: {
      src: "/projects/HandleAudioQueue.webp",
      width: 1200,
      height: 800,
      alt: {
        uk: "HandleAudioQueue.webp",
        en: "HandleAudioQueue.webp",
      },
    },
    stack: [
      "n8n",
      "Google Sheets",
      "Workflow Management",
      "OpenRouter",
      "Large Language Models (LLM)",
      "AssemblyAI",
      "n8n DataTable",
    ],
  },
  {
    slug: "ai-powered-short-form-video-content-factory",
    order: 60,
    year: 2026,
    category: "automation",
    href: "https://quill-haze-d51.notion.site/AI-Powered-Short-Form-Video-Content-Factory-3a4c423a711e805ca46dc4e82661a70e",
    kind: {
      uk: "Автоматизація на базі штучного інтелекту",
      en: "Artificial intelligence-based automation",
    },
    title: {
      uk: "Фабрика короткометражного відеоконтенту на базі ШІ",
      en: "AI-based short video content factory",
    },
    summary: {
      uk: "Фабрика коротких відеоконтентів на базі штучного інтелекту, для соц мереж та маркетингу.",
      en: "A factory of short video content based on artificial intelligence, for social networks and marketing.",
    },
    cover: {
      src: "/projects/AI-Powered Short-Form Video Content Factory.webp",
      width: 1200,
      height: 800,
      alt: {
        uk: "AI-Powered Short-Form Video Content Factory",
        en: "AI-Powered Short-Form Video Content Factory",
      },
    },
    stack: [
      "n8n",
      "OpenRouter",
      "fal.ai",
      "JSON2Video",
      "Blotato",
      "Google Sheets",
    ],
  },
] satisfies readonly ProjectInput[];
